id: I72E3A741
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T08:00:20+00:00'
last_modified: '2022-06-08T08:18:04.103772+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN525
  title: རྒྱལ་སྲས་ལག་ལེན་གྱི་རྩ་འགྲེལ།
  author: ཐུབ་བསྟན་ཆོས་ཀྱི་གྲགས་པ།
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FA88:
      image_group_id: I3CN8488
      title: ''
      total_pages: 254
      order: 1
      base_file: FA88.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
