id: P008259
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 13:11:32.288893
source_metadata:
  id: bdr:W3CN525
  title: རྒྱལ་སྲས་ལག་ལེན་གྱི་རྩ་འགྲེལ།
  author: ཐུབ་བསྟན་ཆོས་ཀྱི་གྲགས་པ།
  volumes:
    6e190327e22d493c8f3a6f2103a542ab:
      image_group_id: I3CN8488
      title: ''
      volume_number: 1
      total_pages: 254
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
