id: opecha:P008259
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN525
  title: རྒྱལ་སྲས་ལག་ལེན་གྱི་རྩ་འགྲེལ།
  volume: ''
  author: ''
ebook_metadata:
  title: རྒྱལ་སྲས་ལག་ལེན་གྱི་རྩ་འགྲེལ།
  authors:
  sku: P000101
  cover: LEK-PHI-001.jpg
  layers:
  - Chapter
  - Pagination
  - Citation
  - Sabche
